[project]
name = "kleinduimpje"
version = "0.1.0"
description = "Playing around with Garmin files on Marimo"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fitparse>=1.2.0",
    "folium>=0.20.0",
    "gpxpy>=1.6.2",
    "marimo>=0.18.0",
]
